### ISSUE TITLE
[RFE] Add Community General (Galaxy) collection plugin 'json_query' to Red Hat Automation Hub

### ISSUE THREAD

**Issue by tesseract-rh** [ansible-collections/ansible.posix#110]
##### SUMMARY
Add the community-supported 'json_query' plugin to Red Hat Automation Hub.

##### ISSUE TYPE
On behalf of one of our customers, can we please look into adding the json_query plugin to Automation Hub:
https://galaxy.ansible.com/community/general

##### COMPONENT NAME
plugin: json_query
collection: Community General (Galaxy)

##### ADDITIONAL INFORMATION
We've discussed the topic briefly with Richard (Henshall) and he wanted to have an RFE for it.
Apologies in advance if this is the wrong place for this RFE (it was our best guest with the RH ansible support team).

```yaml

```

**Comment by abenokraitis** [comment]
A few things need to happen before this is considered:
1.  `json_query` must first move out of `community.general` 
2.  resolve any dependent packages, such as `python-jmespath`
3.  Full code evaluation for supportability and quality

**Comment by tesseract-rh** [comment]
Do we already have any plans/updates for this RFE?

**Comment by Akasurde** [comment]
Is there any specific requirement from the `json_query` which can not be satisfied? You can always use `selectattr` or `rejectattr` which are part of Jinja itself.

**Comment by pabelanger** [comment]
+1 we have integration testing in amazon.aws that use this filter. If we are not going to support it, we then need a way to upgrade any AH collection today, that's testing depends on it:

  https://github.com/ansible-collections/amazon.aws/issues/289

**Comment by pabelanger** [comment]
> Is there any specific requirement from the `json_query` which can not be satisfied? You can always use `selectattr` or `rejectattr` which are part of Jinja itself.

I've never worked with those functions, how would you go about doing:

```
vpc_cidr_a in (result.vpc | community.general.json_query("cidr_block_association_set[*].cidr_block") | list)
```

**Comment by richm** [comment]
I'm not sure what the input looks like, nor the format you expect for the output, but how about this: https://gist.github.com/richm/3fed3cbf15e8e891fc59892a5937ae18

The system roles team recently went through this exercise - getting rid of several places where `json_query` was used in favor of `selectattr/rejectattr/map`.  I think there was one place we had to resort to jinja looping, but otherwise it was pretty straightforward.  We don't have any deeply nested or otherwise complex data structures to parse.

In addition, all of the roles now support RHEL7 which uses jinja 2.7 - one of the biggest challenges was that we could not use `equals` or `==` or `equalto` with `selectattr` - we could not use `selectattr('key', '==', 'value')` - fortunately the `match` filter provided with ansible can handle this case - `selectattr('key', 'match', '^value$')`

**Comment by pierre-amadio** [comment]
The roles support is not as convenient as the json query according to the feedback i received in the linked support ticket:

#######
json_query is very usefull because for same key in a json, I do not have to loop to find the correct value. 

For example for having the value of key "param_os", I only put that one line in my code :
param_os: "{{ request_item | community.general.json_query('variables[?key==`param_os`].value | [0]') }}"

I do not know any other module in Automation hub to make it.

Json example :
----------------------------------------------------------------
request_item:
  variables:
    - key: param_os
      value: Win2019
      displayValue: Windows 2019
    - key: param_impact
      value: ''
      displayValue: ''
    - key: param_timing
      value: ''
      displayValue: ''
-----------------------------------------------
#######

If including the json_query plugin to the galaxy collection is not going to happen, would it be possible to officially close this issue so i can relay it in the linked support ticket ?
