### ISSUE TITLE
provide additional flag for mount module to comment out neccessary line from /etc/fstab

### ISSUE THREAD

**Issue by bilalcaliskan** [ansible-collections/ansible.posix#224]
##### SUMMARY
[mount](https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/mount.py) module successfully mounts and removes the mount from filesystem. Module also successfully handles /etc/fstab. But assume that you want to ensure swap is absent on the system. If you pass `state=absent` to the module, it completely removes the mount entry from /etc/fstab. Instead it would be great if module could somehow commented out the neccessary line instead of removing it completely. It would be great if you dont want to completely remove an fstab entry without backing up whole fstab file.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
[mount](https://github.com/ansible-collections/ansible.posix/blob/main/plugins/modules/mount.py) module

##### ADDITIONAL INFORMATION
We can provide additional boolean flag which is only usable on `state=absent` condition like `comment` which is false by default. And then we can call the module like below:
```yaml
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
    comment: true
```

**Comment by quidame** [comment]
Hi @bilalcaliskan , do you plan to raise a PR to implement this ?

In my opinion, keeping tracks of commented entries could bloat the module for no real benefit: the need to consistently compare more than 2 states and to take decisions from that could make the module harder to maintain.

With your example: say a swap space has been enabled on host A, and not on host B. Now we want to disable it on all hosts. If we do it with `comment=true`, we get different results on hosts A and B, because initial states were different. This shouldn't. This shouldn't, because a task describes a state we want. Not the state we want from a previous state we know about, but just the sate we want, ***blindly***. So, to get the same result on host B, the module should **add** a commented entry... whereas `state` is *absent*...

Once done, what could happen when we want to enable the swapfile ? Uncomment the line if it exists, or add it otherwise ? What to do if there is a commented entry that is almost the same, but not fully the same ? with the same device, and another option set ? Should the commented line be left untouched and kept as backup, and a new line added ? or should the commented line be uncommented and updated ? (I assume that commented lines may be reused by the module: if they're only for humans, the module should not manage them at all).

I'm not sure there is a real benefit to translate these questions and their answers into python :)

Also, note that the current version of the `mount` module accepts the `boot` option, which on Linux and BSD adds or removes the `noauto` flag to/from fstab's mount options.
