### ISSUE TITLE
skippy callback in 1.0.0 uses deprecation by Ansible version (and not by date or collection version)

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/ansible.posix#62]
##### SUMMARY
See https://github.com/ansible-collections/ansible.posix/blob/master/plugins/callback/skippy.py#L17

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/callback/skippy.py

##### ANSIBLE VERSION
```paste below
devel
```

**Comment by maxamillion** [comment]
@felixfontein are there docs on what the expected migration is here? I feel like that should be written down somewhere, but I'm not finding it in any of these places: https://docs.ansible.com/ansible/latest/dev_guide/module_lifecycle.html, https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html, https://github.com/ansible-collections/overview (I knew the formatting once upon a time but it's been a good 6 months since I changed one and now I don't remember)

**Comment by felixfontein** [comment]
@maxamillion the Ansible version needs to be replaced either by a collection version or by a date. AFAIK the Ansible Content Team decided to deprecate by date and not by version, so `removed_in` should be removed and replaced by `removed_at_date: YYYY-MM-DD` (see https://github.com/ansible-collections/overview/issues/45#issuecomment-645619042 for the syntax). Which date to use I don't know, that depends on the deprecation policy the Ansible Content Team is using.
