### ISSUE TITLE
Firewall modules splitted between collections

### ISSUE THREAD

**Issue by mhalano** [ansible-collections/ansible.posix#86]
##### SUMMARY
Firewalld, the RedHat family default firewall, is in this collection, but other firewalls, more specifically iptables and ufw are in other collections. I think all Linux firewall modules should belong to just one collection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
firewalld

##### ANSIBLE VERSION

```
ansible 2.10.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mhalano/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

```

##### CONFIGURATION
No changes

##### OS / ENVIRONMENT
Ubuntu 20.04 LTS

##### STEPS TO REPRODUCE
You can find firewalld module at this collection, ufw at community.general and iptables at standard modules.

##### EXPECTED RESULTS
All Linux firewall modules should belong to the same collection

##### ACTUAL RESULTS
Each one of the three main firewalls are in a different collection.

**Comment by maxamillion** [comment]
Hello! Thank you for opening an issues ticket. :)

While I don't inherently disagree with the premise that all firewall related modules should be in the same collection, this is largely a side effect of what contributors are working on what modules ended up within which Collection as a knock on effect. Part of the goal of [Ansible Collections](https://github.com/ansible-collections/overview) is to provide freedom and flexibility in the development cycle and also allow users to get updates, feature enhancements, and bugfixes to the modules they care about faster (Ansible previously did not allow feature enhancements outside of the 6 month release timeline). Currently those of us working on this collection are not historically focused on the code base of the other firewall related modules which is why they weren't brought over into this collection. This could absolutely change in the future but that's not the case today. I'll leave this open as a feature request so that it can be evaluated and I'll reach out to the other maintainers to see if they'd be willing to move their content over to this collection so it's all in one location.

**Comment by gundalow** [comment]
@mhalano Is the fact that the firewall modules are split across different collections causing you pain as a playbook author, or someone running `ansible-playbook`?

If you are using `ansible 2.10` package then you will have access to everything

If you are using `ansible-base`, then you are correct, you'll need to install `community.general` and `ansible.posix` collections

**Comment by mhalano** [comment]
@gundalow As playbook author. I think would be better if firewall modules are all at the same collection, but we have three modules in three different collections.

**Comment by quidame** [comment]
@mhalano in fact there are 4 modules in 3 collections. `iptables_state` is the last one, in `community.general` collection (as `ufw`).

I understand the request, and I could move the module I maintain to another collection, but I doubt `ansible.builtin.iptables` will move too. And it doesn't make sense for the 3 others to move to `ansible.builtin`, in my opinion.

**Comment by saito-hideki** [comment]
Hi all :)
It has been over three years since the last comment on this issue.
This matter involves multiple collections, so I think it should be discussed first on the [Ansible Forum](https://forum.ansible.com/).
Therefore, I will close this issue. If you have any comments, please let me know.
